import os

PAYPAL_CLIENT_ID = os.getenv("PAYPAL_CLIENT_ID", "AYO6e64gj9Jc_T9QlKLu5DTdDkFqkdvi0yE9RhA-QiSnYmO4rk3bvmde2AWmyJfCOwMmJVpBZgwQXcF3")
PAYPAL_CLIENT_SECRET = os.getenv("PAYPAL_CLIENT_SECRET", "EM7rFCl8OgylPOJcGZdHVPR8pysVm2_1SLfdkY8dczQ6P2mHH2v59H977u9b_kBK2MYKaFvx8pQSKqYE")
PAYPAL_MODE = "sandbox"